branches:
  only:
    - master
    
configuration: release

version: 1.3.0.{build}
image: Visual Studio 2017

cache:
  - packages -> **\packages.config

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build:
  verbosity: normal
  publish_nuget: true
  publish_nuget_symbols: true
  project: PantherDI.sln

before_build:
  - cmd: nuget restore

deploy:
  - provider: NuGet
    api_key:
      secure: dibSRZV3ymKVhvCw+HGe01juPuirxknhvtcTqJb71d4C0gI801hKgfy6fXUSGNpk

nuget:
  account_feed: true
  project_feed: true
  disable_publish_on_pr: true